// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 23.01.2025, 00:49:58
import configMerger from '@nuxtjs/tailwindcss/merger'

import cfg2 from './../../tailwind.config.ts'
const config = [
	{
		content: {
			files: [
				'/Users/paymei/Documents/github/M2Exchange/components/**/*.{vue,js,jsx,mjs,ts,tsx}',
				'/Users/paymei/Documents/github/M2Exchange/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}',
				'/Users/paymei/Documents/github/M2Exchange/components/**/*.{vue,js,jsx,mjs,ts,tsx}',
				'/Users/paymei/Documents/github/M2Exchange/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}',
				'/Users/paymei/Documents/github/M2Exchange/pages/**/*.{vue,js,jsx,mjs,ts,tsx}',
				'/Users/paymei/Documents/github/M2Exchange/plugins/**/*.{js,ts,mjs}',
				'/Users/paymei/Documents/github/M2Exchange/composables/**/*.{js,ts,mjs}',
				'/Users/paymei/Documents/github/M2Exchange/utils/**/*.{js,ts,mjs}',
				'/Users/paymei/Documents/github/M2Exchange/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}',
				'/Users/paymei/Documents/github/M2Exchange/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}',
				'/Users/paymei/Documents/github/M2Exchange/app.config.{js,ts,mjs}'
			]
		}
	},
	{},
	cfg2
].reduce((acc, curr) => configMerger(acc, curr), {})

const resolvedConfig = config

export default resolvedConfig
